# Generated by Django 3.2.5 on 2022-05-05 19:25

import convener.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convener', '0005_convener_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIC',
            fields=[
                ('convener_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='convener.convener')),
                ('phone_no', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Person-In-Charge',
            },
            bases=('convener.convener',),
            managers=[
                ('objects', convener.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mrun_code', models.CharField(max_length=5)),
                ('cchal_code', models.CharField(max_length=5)),
                ('mrun_slots', models.IntegerField(default=5)),
                ('cchal_slots', models.IntegerField(default=5)),
                ('mrun_taken', models.IntegerField(default=0)),
                ('cchal_taken', models.IntegerField(default=0)),
                ('events', models.ManyToManyField(to='convener.Event')),
                ('person_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organization.pic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
