# Generated by Django 3.2.5 on 2022-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pic',
            options={'verbose_name': 'Person-In-Charge', 'verbose_name_plural': 'Persons-In-Charge'},
        ),
        migrations.AlterField(
            model_name='pic',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
