# Generated by Django 3.2.5 on 2022-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20220505_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cchal_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mrun_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
