# Generated by Django 3.2.5 on 2022-08-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20220813_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='body',
            field=models.TextField(default='Default Value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
