# Generated by Django 3.2.5 on 2022-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='motto',
            field=models.CharField(default="Let's do this!", max_length=50),
            preserve_default=False,
        ),
    ]
