# Generated by Django 3.2.5 on 2022-05-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convener',
            name='username',
        ),
    ]
