# Generated by Django 3.2.5 on 2022-05-03 19:10

import convener.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convener', '0002_remove_convener_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='convener',
            managers=[
                ('objects', convener.models.UserManager()),
            ],
        ),
    ]
