# Generated by Django 3.2.5 on 2022-05-03 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convener', '0003_alter_convener_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('total_mrun_slots', models.IntegerField(verbose_name='Total Mass Run Slots')),
                ('total_cchal_slots', models.IntegerField(verbose_name='Total Chief Challenge Slots')),
                ('convener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
