# Generated by Django 3.2.5 on 2022-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convener', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='convener',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
