# Generated by Django 3.2.5 on 2022-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convener', '0006_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('concluded', 'Concluded')], default=('ongoing', 'Ongoing'), max_length=10),
        ),
    ]
